---
env:
    browser: true
    es6: true
    es2021: true
    commonjs: true
    jest: true
    jest/globals: true
extends:
    - "eslint:recommended"
    - "plugin:jest/all"
    - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: latest
    sourceType: module
plugins:
    - "@typescript-eslint"
    - jest
rules:
    indent:
        - error
        - 4
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - double
    semi:
        - error
        - always
    jest/no-disabled-tests: "warn"
    jest/no-focused-tests: "error"
    jest/no-identical-title: "error"
    jest/prefer-to-have-length: "warn"
    jest/valid-expect: "error"
